### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by JohnLeM** [JohnLeM/codpy_alpha#4]
From [N'goran Sylvain N'dri](https://www.linkedin.com/in/ACoAAC9Hd1sBpzzeW3av5NXUbsErF-QOwOoMl2Q)

![1667608596463](https://user-images.githubusercontent.com/5907288/200113764-429dc7dc-68e6-4000-8b36-3e515c7d06e2.png)

**Comment by JohnLeM** [comment]
Hello, 

I can't reproduce your issue. Could you describe how you attempted to install codpy ? Did you follow the instructions at https://pypi.org/project/codpy/ ?
Best

**Comment by tonyporsche123** [comment]
I created a virtual environment. then I proceeded by pip install codpy in the terminal

**Comment by JohnLeM** [comment]
Did you create your venv using python 3.9.7 ?

**Comment by tonyporsche123** [comment]
Using python 3.11

**Comment by JohnLeM** [comment]
That's probably the point : we are currently using 3.9.7. Please upgrade your python to 3.9.7, as pointed in the installation guidelines and try again. I close this issue, please report any other issues using this link https://github.com/JohnLeM/codpy_alpha/issues.
Thank you for your feedback

**Comment by JohnLeM** [comment]
That's probably the point : we are currently using 3.9.7. Please upgrade your python to 3.9.7, as pointed in the installation guidelines and try again. I close this issue, please report any other issues using this link https://github.com/JohnLeM/codpy_alpha/issues. If you really need a python 3.11 setting, please report it as an enhancement request
Thank you for your feedback

**Comment by tonyporsche123** [comment]
Hello Sir,
I was able to install the codpy.
I want to set up a reverse stress test model. How to do it
