### ISSUE TITLE
codpy installation issue related to codpydll package

### ISSUE THREAD

**Issue by FaridBouakline** [JohnLeM/codpy_alpha#5]
I tried to install codpy package using pip function  and manual way (downloading zip file from github )but got an error message related to codpydll package 

pip attempt gave me an Error message :" could not find a version that satisfies the requirement codpydll (from versions: none)

seems the conflict is caused  codpy version (0.1.8 to 0.0.5) depending all on codpydll.

This kind of issue is generally common for versioning issue  and advice s generally to  loosen the range of package specified or remove the inadequate version (which i found a bit odds in this context).

the manual installation attempt  (zip file ) but this wasn't successful either.

Same error message associated to the lack of codpy version satisfying  codpydll =0.1.1 

My understanding is that codpydll  is a component of the initial package and should be included.

HAve you ever faced similar issue or is something wrong in my setting?

**Comment by JohnLeM** [comment]
Farid,

Hello.
Thank you for downloading codpy.
This issue probably came from your python version. This pre alpha version
of codpy run for python 3.9.7.
We are working on a multi-version, multi-platform, but it is not yet ready.


Le mar. 20 déc. 2022 à 22:05, FaridBouakline ***@***.***> a
écrit :

**Comment by JohnLeM** [comment]
I filled an enhancement request to handle multi-platform / multi python version. I suggest to close this one to avoid duplicates.

**Comment by FaridBouakline** [comment]
Indeed, this works on my side now . I naively thought >3.9.7 version would work regardless.
Great to hear you are working on the multi-platform/multi python version.
For the LINUX user like me, the installation did require some nasty tweaks before running smoothly.
So far, I got some results as expected.  
In regard, of the request above, I assume you're already aware of some warnings message related  of some functions used (Float64Index, loss function,etc..) not supported in the new version of the packages dependencies?

**Comment by JohnLeM** [comment]
Dear Farid,

Yes, we are aware of several bugs / enhancement for this library. I added
your remarks concerning warnings as bugs.
Indeed, this library went open early this year, mainly to try growing a
community of users, but also to  reassure our clients on the openess aspect
of our tools.
However, we are a small team involved in the maintenance / evolution of
this library, among the tasks involved by our clients. With such few
resources, we currently focus on multi platform/multi python version, and
also to enrich the documentation with other algorithms as kernel-based
encoders.


Le mer. 21 déc. 2022 à 11:49, FaridBouakline ***@***.***> a
écrit :

**Comment by JohnLeM** [comment]
By the way, we are very interested by the linux tweaks that you developped,
as we don't have any experience with this OS. Do not hesitate to contact us
!

Le mer. 21 déc. 2022 à 11:49, FaridBouakline ***@***.***> a
écrit :

**Comment by FaridBouakline** [comment]
Not really developed anything myself here  , but rather spending time to find way to test  your package without being cursed by Windows OS. Finally found  [Wine](https://www.winehq.org/) (stands for wine is not an emulator) is a free and open source compatibility layer allowing apps developed for windows to run on Unix like operating systems.

Though not perfect,and distro (type of OS ) dependent, once installed properly, it is easier  and lighter  to use than  virtual environment.
I however needed to reinstall python for windows in with the adequate  package in my case.
So far , this sounds fine  but would be cautious to consider an extensive usage.
